name: stereoscopeEnv
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - cairo=1.16.0
  - eigen=3.4.0
  - expat=2.6.4
  - fontconfig=2.14.1
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - hdf5=1.14.5
  #- icc_rt=2022.1.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - krb5=1.20.1
  - lerc=4.0.0
  - libabseil=20240116.2
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.78.4
  - libiconv=1.16
  - libmpdec=4.0.0
  - libogg=1.3.5
  - libpng=1.6.39
  - libpq
  - libprotobuf=4.25.3
  - libtiff=4.5.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxml2
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - numpy=2.2.2
  - numpy-base=2.2.2
  - opencv
  - openjpeg=2.5.2
  - openssl=3.0.15
  - pcre2=10.42
  - pip=25.0
  - pixman=0.40.0
  - python
  - python_abi=3.13
  - qt-main
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tzdata=2025a
  #- vc
  #- vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - cachetools==5.5.1
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - google-api-core==2.24.1
      - google-api-python-client==2.161.0
      - google-auth==2.38.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.1
      - googleapis-common-protos==1.67.0
      - httplib2==0.22.0
      - idna==3.10
      - oauthlib==3.2.2
      - proto-plus==1.26.0
      - protobuf==5.29.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pyparsing==3.2.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - uritemplate==4.1.1
      - urllib3==2.3.0
